# Generated by Django 5.2 on 2025-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driverprofile_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
