# Generated by Django 5.2 on 2025-05-19 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_alter_driverprofile_experience_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(default='Black', max_length=50),
        ),
    ]
