# Generated by Django 5.2 on 2025-05-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_passengerprofile_cnic_passengerprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
