# Generated by Django 5.2.2 on 2025-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_passengerprofile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passengerprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
